# Config for the conversion topics and the message limits
conversion:
  topics:
    origin_cmd_topic: /ros2can/send/dv_control_target
    target_cmd_topic: /fssim/cmd
    origin_odom_topic: /fssim/base_pose_ground_truth
    target_odom_topic: /dlio/odom_node/odom
    
  limits:
    max_target_speed: 90
